// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsarFE85AFv0uK47ufnRu-QX5dzTOat7U',
    appId: '1:195377364952:web:4aca796a4fc4b606eb3cad',
    messagingSenderId: '195377364952',
    projectId: 'quickjot-b8207',
    authDomain: 'quickjot-b8207.firebaseapp.com',
    storageBucket: 'quickjot-b8207.firebasestorage.app',
    measurementId: 'G-KRTHTGQZGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGitxGetyQ7ffKg25KdRqj8PeQCSDWzp8',
    appId: '1:195377364952:android:ce19674aaa199a38eb3cad',
    messagingSenderId: '195377364952',
    projectId: 'quickjot-b8207',
    storageBucket: 'quickjot-b8207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv5GMvciuMTD0i3Y2BGiyBtK_iS40PEZc',
    appId: '1:195377364952:ios:e917421a51987bceeb3cad',
    messagingSenderId: '195377364952',
    projectId: 'quickjot-b8207',
    storageBucket: 'quickjot-b8207.firebasestorage.app',
    iosBundleId: 'com.example.quickjot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv5GMvciuMTD0i3Y2BGiyBtK_iS40PEZc',
    appId: '1:195377364952:ios:e917421a51987bceeb3cad',
    messagingSenderId: '195377364952',
    projectId: 'quickjot-b8207',
    storageBucket: 'quickjot-b8207.firebasestorage.app',
    iosBundleId: 'com.example.quickjot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsarFE85AFv0uK47ufnRu-QX5dzTOat7U',
    appId: '1:195377364952:web:2452f990d7889002eb3cad',
    messagingSenderId: '195377364952',
    projectId: 'quickjot-b8207',
    authDomain: 'quickjot-b8207.firebaseapp.com',
    storageBucket: 'quickjot-b8207.firebasestorage.app',
    measurementId: 'G-6EBQLWEKJ6',
  );

}